apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - image: rconway/jupyter
        name: jupyter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter
  name: jupyter
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter
  namespace: default
spec:
  rules:
  - host: jupyter.test.192.168.49.2.nip.io
    http:
      paths:
      - backend:
          serviceName: jupyter
          servicePort: 80
